### ISSUE TITLE
Cannot import Cmd from animanager.cmd

### ISSUE THREAD

**Issue by eightys3v3n** [darkfeline/animanager#10]
Upon installing with `pip install --user animanager` or `sudo pip install animanager` and running with `animanager` I am faced with the error as follows.

```
Traceback (most recent call last):
  File "/usr/bin/animanager", line 5, in <module>
    from animanager.__main__ import main
  File "/usr/lib/python3.8/site-packages/animanager/__main__.py", line 25, in <module>
    from animanager.animecmd import AnimeCmd
  File "/usr/lib/python3.8/site-packages/animanager/animecmd/__init__.py", line 32, in <module>
    from animanager.cmd import Cmd
ImportError: cannot import name 'Cmd' from 'animanager.cmd' (/usr/lib/python3.8/site-packages/animanager/cmd/__init__.py)
```

If I go into `animanager/animecmd/__init__.py` and change `animanager.cmd` to `animanager.cmd.cmd` it succeeds only to fail again at another error similar to this one, and on and on.

Have I setup my environment somehow wrong or is some installation step or project environment setup not mentioned in the installation instructions? It seems a lot like the __init__ files are being imported differently on my system than expected and this is leading to all the imports failing.

**Comment by darkfeline** [comment]
If you don't have any attachment to Python, I'd recommend using https://github.com/darkfeline/animanager-go instead.  As stated in the [release notes](https://github.com/darkfeline/animanager/blob/master/NEWS.rst), I'm no longer working on or using the Python version (I will add this info to the README and docs soon).

There aren't formal docs for the Go version, but it works very similarly to the Python version.  I can write some docs since the rewrite is very stable for me now.

**Comment by eightys3v3n** [comment]
Will do, thank you.

Regards, Terrence
